---

- name: Install snmp
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  with_items:
    - snmpd
    - snmp
    - libsnmp-dev

- name: copy config
  copy: src=
